version: "3.3"

services:

  tomcat:
    build: ./tomcat
    ports:
      - "80:8080"
    volumes:
      - data:/usr/local/tomcat/webapps

  warfile-artefact:
     build: ./html
     volumes:
      - data:/usr/local/tomcat/webapps

volumes:
   data:
