version: "3.3"

services:

  tomcat:
    build: ./tomcat-alpine
    ports:
      - "80:8080"
    volumes:
      - data:/usr/local/tomcat/webapps

  warfile-artefact:
     build: ./htmltest
     volumes:
      - data:/tmp/

volumes:
   data: